language: node_js
sudo: false
node_js:
- 0.10.31
- '0.10'
- '0.11'
env:
  global:
  - LOG_LEVEL=error
  - secure: Nto0DJdtm5X9c0UxO3WDc1UJcDMr6iqonzEg8jsbv6WBcKx4QuZTwJQevKxqb6Tn3kiY4EAKMxZkBPUEwAtOSjDNXogOS1WbZZ+8KxcHB5eMqAtRUR0cT4MnyHFxHD/yKzUMlpMLPw9sBRJVXyj1S3oZtgMyvgrxvXbdi6gFCnI=
  - secure: TOpGyGYih+aDCljsnk93VEe+FRh8Ehh56Ycs1vFglWbC5HukgQ6gjrgpn28JUN1pV+XYIhfuDcvRNXLOBP4mX80c3LwClOh4AXzOf1VJcJyIGRVMCuCK9UgS37e/RsxgFczcu/MzJG/rCbt0lR46t6FQhqEBzmsbJV0oL5zA94M=
matrix:
  fast_finish: true
script: npm test
after_script: npm run-script inspect
addons:
  artifacts:
    key:
      secure: IkWCXkSK6sl0M0HGCBM4mHhKheIGr4I6wUHu5rFaAC/+korYPPxdbYp85XnpcLlKj58warZr7F8XxftlLP9M14Jo05uWRF0GWbPrjljWv/W36K5p5H1eKkICtZW+lYlZFVInJ+ifCn6/vPij1BZ+IUSm9rj4AmVhdQBLRbRp3iQ=
    secret:
      secure: S/e3GB6UnhNQSNi4fJpnqVn4yxgXsZY/bYSJjm3MPdJF8t2onzoYUo7zHbgpNVxEwvqMZjknFQ3ZEkoKs+5JjDPbsTHTCbk5l0Kg3eTpr1FUDrFAzEGcw5jhQkMKFXTn++Ob99UByK5pDo92MLasIx83d1PqmYl+Ya15hDK6XQo=
    bucket: elements-travis-artifacts
    debug: true
    paths:
    - $(find reports/* -print | tr "\n" ":")
    - $(find coverage/* -print | tr "\n" ":")
